# Generated by Django 2.2.7 on 2019-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIBRO', 'Saibro'), ('HARD', 'Hard')], max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('pago', 'Paga'), ('pendente', 'Pendente'), ('cancelado', 'Cancelada')], default='pendente', max_length=32)),
                ('duracao', models.PositiveIntegerField(default=0)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('inicioEm', models.DateTimeField(blank=True, null=True)),
                ('fimEm', models.DateTimeField(blank=True, null=True)),
                ('canceladoEm', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
