# Generated by Django 2.2.7 on 2019-11-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
